### ISSUE TITLE
認証、電話番号の方が今時

### ISSUE THREAD

**Issue by ryuseikurata** [lcnem/lcnem-credit#13]
**Is your feature request related to a problem? Please describe.**
* 電話番号の方が、他のアプリ見てもあるような気がします。

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by YuKimura45z** [comment]
イマドキっていうのは議論の土台としてはクソみたいな提案やけど、どうせ電話番号も収集しないといけないのであればパスワードたぶん不要の電話番号認証のほうが賢いだろうね

**Comment by Dragon-taro** [comment]
いちいち電話番号で認証するサービスみたことない
firebase的にはいける

**Comment by ryuseikurata** [comment]
アカウント複製
メールアドレス　無限
電話番号　有限
